name: deploy
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - master
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Deploy to firebase
        run: |
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
          chmod +x ./firebase_bin
          ./firebase_bin deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # - name: Purge CDN
      #   run: |
      #     curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
      #     -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_AUTH }}" \
      #     -H "Content-Type: application/json" \
      #     --data '{"purge_everything":true}'
