name: deploy
on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [master]
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history; so we get the last tagged git commit
      - uses: actions/cache@v3
        with:
          path: .firebase
          key: firebase-${{ github.run_id }}
          restore-keys: |
            firebase-
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm run build
      - name: Deploy to firebase
        run: |
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
          chmod +x ./firebase_bin
          ./firebase_bin deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # - name: Purge CDN
      #   run: |
      #     curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
      #     -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_AUTH }}" \
      #     -H "Content-Type: application/json" \
      #     --data '{"purge_everything":true}'
